
spring:

  h2:
    console:
      enabled: true

  sql:
    init:
      schema-locations: classpath*:table/schema.sql
#      data-locations: classpath*:table/data.sql
      mode: always

  datasource:
    #    url: jdbc:mysql://localhost:3306/chalkak?serverTimezone=UTC&charsetEncoding=UTF-8
    url: jdbc:h2:mem:chalkak;DB_CLOSE_DELAY=-1
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.h2.Driver
    #    username: root
    #    password: 1q2w3e4r!@
    username: sa
    password:

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: h2

  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: "chat-test"
    consumer:
      group-id: "group_1"
      auto-offset-reset: earliest
      enable-auto-commit: true
      max-poll-records: 10